package Vista;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;
import SJF.Cola;
import java.awt.Font;
import java.awt.Color;
import java.awt.Component;

import javax.swing.SwingConstants;
import javax.swing.JButton;
import javax.swing.JComponent;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JScrollPane;
import java.awt.Dimension;

/**
 *
 * AUTOR ALEJANDRO MORALES
 */
public class Ventana extends JFrame {

    VentanaProceso vProceso;
    SJF sjf;

    public Ventana() {
        initComponents();
        btnPausar.setEnabled(false);
        vProceso = new VentanaProceso(jTableProcesos, tiempo_real, txaConsola);
        
        JButton btnSalir = new JButton();
        btnSalir.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		System.exit(0);
        	}
        });
        btnSalir.setText("Salir");
        btnSalir.setFont(new Font("Arial", Font.ITALIC, 12));
        btnSalir.setBackground(Color.MAGENTA);
        btnSalir.setBounds(20, 163, 150, 25);
        pnlArriba.add(btnSalir);
        
        JLabel label = new JLabel();
        label.setText("Rafaga ejecutada: ");
        label.setFont(new Font("Arial", Font.ITALIC, 12));
        label.setBounds(20, 296, 105, 16);
        pnlArriba.add(label);
        
        JLabel label_1 = new JLabel();
        label_1.setText("0");
        label_1.setFont(new Font("Arial", Font.ITALIC, 12));
        label_1.setBounds(140, 296, 63, 20);
        pnlArriba.add(label_1);
        
        label_2 = new JLabel();
        label_2.setText("Tiempo Rafaga:");
        label_2.setFont(new Font("Arial", Font.ITALIC, 12));
        label_2.setBounds(20, 313, 135, 16);
        pnlArriba.add(label_2);
        
        label_3 = new JLabel();
        label_3.setText("0");
        label_3.setFont(new Font("Arial", Font.ITALIC, 12));
        label_3.setBounds(140, 314, 62, 14);
        pnlArriba.add(label_3);
        
        JLabel lblNewLabel = new JLabel("Proceso Bloqueado");
        lblNewLabel.setBounds(815, 82, 97, 40);
        pnlArriba.add(lblNewLabel);
        
        JLabel lblTiempo = new JLabel("Tiempo de bloqueo\r\n\r\n\r\n");
        lblTiempo.setBounds(815, 127, 141, 40);
        pnlArriba.add(lblTiempo);
        
        JLabel lblNewLabel_1 = new JLabel("0");
        lblNewLabel_1.setBounds(922, 97, 46, 14);
        pnlArriba.add(lblNewLabel_1);
        
        label_4 = new JLabel("0");
        label_4.setBounds(922, 140, 46, 14);
        pnlArriba.add(label_4);
        pack();
    }

    public JTable getjTable1() {
        return tblGannt;
    }

    public void setjTable1(JTable jTable1) {
        this.tblGannt = jTable1;
    }

    public JTable getjTableProcesos() {
        return jTableProcesos;
    }

    public void setjTableProcesos(JTable jTable1) {
        this.tblGannt = jTableProcesos;
    }

    public JLabel getTiempo_real() {
        return tiempo_real;
    }

    public void setTiempo_real(JLabel tiempo_real) {
        this.tiempo_real = tiempo_real;
    }

    //public JLabel getCpu_nuevo() {
      //  return cpu_nuevo1;
    //}

    //public void setCpu_nuevo(JLabel cpu_nuevo) {
      //  this.cpu_nuevo1 = cpu_nuevo;
    //}

    //public JTextArea getTexto_diagrama() {
      //  return texto_diagrama;
    //}

    //public void setTexto_diagrama(JTextArea texto_diagrama) {
      //  this.texto_diagrama = texto_diagrama;
    //}

    public JLabel getProcesos_en_ejecucion() {
        return procesos_en_ejecucion;
    }

    public void setProcesos_en_ejecucion(JLabel procesos_en_ejecucion) {
        this.procesos_en_ejecucion = procesos_en_ejecucion;
    }

    //public JTextArea getTexto_listos() {
      //  return texto_listos;
    //}

    //public void setTexto_listos(JTextArea texto_listos) {
      //  this.texto_listos = texto_listos;
    //}

   /* public JLabel getTiempo_cpu() {
        return tiempo_cpu;
    }

    public void setTiempo_cpu(JLabel tiempo_cpu) {
        this.tiempo_cpu = tiempo_cpu;
    }

    public JLabel getTotal_listos() {
        return total_listos;
    }

    public void setTotal_listos(JLabel total_listos) {
        this.total_listos = total_listos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        pnlArriba = new javax.swing.JPanel();
        lblBienvenida = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();
        btnIniciar.setEnabled(false);
        btnPausar = new javax.swing.JButton();

        jPanel2 = new javax.swing.JPanel();
        procesos_en_ejecucion = new javax.swing.JLabel();

        lblEnEjecucion = new javax.swing.JLabel();
        tiempo_real = new javax.swing.JLabel();
        txaConsola = new JTextArea();
        lblTiempoTotal = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblGannt = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableProcesos = new javax.swing.JTable();
        Component jScrollPane42 = new javax.swing.JScrollPane();
        JComponent jTableBloqueados = new javax.swing.JTable();
        btnInsertar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));
        setFocusTraversalPolicyProvider(true);
        setForeground(new java.awt.Color(204, 255, 204));
        setLocation(new java.awt.Point(0, 0));
        pack();

        pnlArriba.setBackground(Color.GREEN);
        pnlArriba.setLayout(null);

        lblBienvenida.setBackground(Color.GREEN);
        lblBienvenida.setFont(new Font("Arial", Font.ITALIC, 49)); 
        lblBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBienvenida.setText("SO");
        pnlArriba.add(lblBienvenida);
        lblBienvenida.setBounds(0, 10, 1030, 40);

        btnIniciar.setBackground(Color.MAGENTA);
        btnIniciar.setFont(new Font("Arial", Font.ITALIC, 12)); 
        btnIniciar.setText("Simular");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciar(evt);
            }
        });
        pnlArriba.add(btnIniciar);
        btnIniciar.setBounds(20, 91, 150, 25);

        btnInsertar.setBackground(Color.MAGENTA);
        btnInsertar.setFont(new Font("Arial", Font.ITALIC, 11)); // NOI18N
        btnInsertar.setText("Nuevo Proceso");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertar(evt);
            }
        });
        pnlArriba.add(btnInsertar);
        btnInsertar.setBounds(20, 61, 150, 23);

        btnPausar.setBackground(Color.MAGENTA);
        btnPausar.setFont(new Font("Arial", Font.ITALIC, 12)); // NOI18N
        btnPausar.setText("Parar");
        btnPausar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPausar(evt);
            }
        });
        pnlArriba.add(btnPausar);
        btnPausar.setBounds(20, 121, 150, 25);

        jPanel2.setBackground(Color.GREEN);
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        procesos_en_ejecucion.setFont(new java.awt.Font("Centaur", 1, 12)); 
        procesos_en_ejecucion.setText("0");
        jPanel2.add(procesos_en_ejecucion);
        procesos_en_ejecucion.setBounds(149, 27, 41, 16);

        lblEnEjecucion.setFont(new Font("Arial", Font.ITALIC, 12)); 
        lblEnEjecucion.setText("Proceso en ejecucion: ");
        jPanel2.add(lblEnEjecucion);
        lblEnEjecucion.setBounds(10, 26, 140, 16);

        tiempo_real.setFont(new java.awt.Font("Centaur", 1, 12)); 
        tiempo_real.setText("0");
        jPanel2.add(tiempo_real);
        tiempo_real.setBounds(150, 10, 24, 16);

        lblTiempoTotal.setFont(new Font("Arial", Font.ITALIC, 12)); 
        lblTiempoTotal.setText("Tiempo Total:");
        jPanel2.add(lblTiempoTotal);
        lblTiempoTotal.setBounds(10, 10, 122, 16);

        pnlArriba.add(jPanel2);
        jPanel2.setBounds(20, 213, 170,75);

        jScrollPane8.setBackground(new java.awt.Color(255, 255, 0));
        txaConsola.setBackground(new java.awt.Color(204, 255, 204));
        //txaConsola.setBounds(730, 70, 260, 255);
        txaConsola.setFont(new java.awt.Font("Centaur", 1, 11));
        pnlArriba.add(txaConsola);

        jScrollPane7.setToolTipText("");

        tblGannt.setAutoCreateRowSorter(true);
        tblGannt.setFont(new java.awt.Font("Arial", Font.ITALIC, 12)); 
        tblGannt.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                    {"1", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {"2", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {"3", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {"4", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {"5", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {"6", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {"7", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {"8", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {"9", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {"10", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {"11", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {"12", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {"13", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {"14", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {"15", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {"16", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {"17", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {"18", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {"19", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {"20", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {"21", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {"22", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {"23", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {"24", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {"25", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
                },
                new String[]{
                    "P", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "TE", "TR"
                }
        ));
        tblGannt.setToolTipText("");
        tblGannt.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblGannt.setColumnSelectionAllowed(true);
        tblGannt.setMaximumSize(new java.awt.Dimension(800, 416));
        tblGannt.setMinimumSize(new java.awt.Dimension(800, 416));
        tblGannt.setPreferredSize(new java.awt.Dimension(2200, 416));
        jScrollPane7.setViewportView(tblGannt);
        tblGannt.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        pnlArriba.add(jScrollPane7);
        jScrollPane7.setBounds(20, 340, 980, 200);

        jScrollPane3.setPreferredSize(new java.awt.Dimension(469, 416));

        jTableProcesos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTableProcesos.setFont(new java.awt.Font("Arial", 1, 12)); 
        jTableProcesos.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null}
                },
                new String[]{
                    "Proceso", "T. Llegada", "T. Rafaga", "T. Ejecucion", "T. Final", "T. Retorno", "T. Espera", "Prioridad"
                }
        ));

        jTableProcesos.setEnabled(false);
        jTableProcesos.setMaximumSize(new java.awt.Dimension(2147483647, 130));
        jTableProcesos.setMinimumSize(new java.awt.Dimension(750, 130));
        jScrollPane3.setViewportView(jTableProcesos);

        pnlArriba.add(jScrollPane3);
        jScrollPane3.setBounds(200, 61, 575, 255);
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnlArriba, javax.swing.GroupLayout.PREFERRED_SIZE, 1030, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnlArriba, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

    }// </editor-fold>                        

    private void btnSeguir(java.awt.event.ActionEvent evt) {
        sjf.resume();
        btnPausar.setEnabled(true);

    }

    private void btnPausar(java.awt.event.ActionEvent evt) {

        sjf.stop();
        btnIniciar.setEnabled(true);
    }

    private void btnIniciar(java.awt.event.ActionEvent evt) {
        Cola cola = new Cola(txaConsola);
        cola = vProceso.getCola();
        sjf = new SJF(cola, this);
        sjf.start();
        btnIniciar.setEnabled(false);
        btnPausar.setEnabled(true);
    }

    private void btnInsertar(java.awt.event.ActionEvent evt) {
        vProceso.setVisible(true);
        btnIniciar.setEnabled(true);
    }

    // Variables declaration - do not modify  
    private JTextArea txaConsola;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnPausar;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblTiempoTotal;
    private javax.swing.JLabel lblEnEjecucion;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pnlArriba;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable tblGannt;
    private javax.swing.JTable jTableProcesos;
    private javax.swing.JLabel procesos_en_ejecucion;
    private javax.swing.JLabel tiempo_real;
    private javax.swing.JButton btnInsertar;
    private JLabel label_2;
    private JLabel label_3;
    private JLabel label_4;
    // End of variables declaration  

    public JTextArea getTxaConsola() {
        return txaConsola;
    }

    public void setTxaConsola(JTextArea txaConsola) {
        this.txaConsola = txaConsola;
    }
}
